### ISSUE TITLE
Mastermind AI - RNN

### ISSUE THREAD

**Issue by beytuuh42** [Jay-boo/gym_env#2]
Hey,

I saw that you raised an issue on this repo, regarding his RL implementation:
https://github.com/egeromin/mastermind

I saw your custom mastermind env and was wondering if you have started working on a RL implementation yet.

**Comment by Jay-boo** [comment]
Hi,
No I don't finish to implement this RL solution. 
But RNN is not the optimal solution for mastermind problem. If you're looking for mastermind RL best solution there is plenty of implementaty of Donald Kruth  .
For the implemantation : https://github.com/nattydredd/Mastermind-Five-Guess-Algorithm
And for the theory: https://betterprogramming.pub/solving-mastermind-641411708d01

Indeed you already know all the rules in the env , so you just need Dynamic Programming.
